version: '3'

services:
  formatter:
    image: peterdavehello/shfmt
    container_name: formatter
    volumes:
      - "$PWD:/work"
    entrypoint:
      - "shfmt"
      - "-i"
      - "2"
      - "-ci"
      - "-sr"
      - "-d"

  linter:
    image: koalaman/shellcheck
    container_name: linter
    volumes:
      - "$PWD:/work"
    entrypoint:
      - "shellcheck"

  coverage:
    build:
      context: ./
      dockerfile: ./build/coverage/Dockerfile
    image: coverage
    volumes:
      - "$PWD:/home/kcov/super_unko"
    working_dir: /home/kcov/super_unko
    entrypoint:
      - ./test.sh
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
